### ISSUE TITLE
Only prints 4 pages of PDF.

### ISSUE THREAD

**Issue by francodem** [drengskapur/colab2pdf#1]
In my recent use, it only generates 4 pages per notebook.

**Comment by jonathanagustin** [comment]
@francodem 

Can you post a share link to a Colab notebook? I just tried generating a PDF and generated 6 pages.

<https://colab.research.google.com/drive/1F_ikqTJK1S6bOstUINfw18FWsU5YnqiS?usp=sharing>

I'm aware of problems related to SVGs, but I can try taking a look into your specific issue. Do you have a Colab link I can try taking look at?
